name: Build and push docker image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build big_db_32bit binaries
      env:
        GOARCH: arm
      run: |
        git clone https://github.com/simonvetter/influxdb.git
        cd influxdb
        git checkout origin/1.8.10+big_db_32bit
        mkdir build
        go build -o build/influx_stress cmd/influx_stress/*.go
        go build -o build/influx_tools cmd/influx_tools/*.go
        go build -o build/influx_inspect cmd/influx_inspect/main.go
        go build -o build/influxd cmd/influxd/main.go
        go build -o build/influx cmd/influx/main.go
        cd ..
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login GHCR
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get docker image version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm/v7
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/influxdb-arm32:${{ steps.get_version.outputs.version }}

